[application]
name = "rr-ui"
default_platform = "web"
asset_dir = "public"
out_dir = "dist"

[web.app]
title = "RR-UI Admin Panel"
base_path = "."

[web.watcher]
reload_html = true
watch_path = ["src"]
script = []

[server]
features = ["server"]
